sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CHECK_CS=true
    - php: 7
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer info

script:
  - composer test
  - if [[ $CHECK_CS == 'true' ]]; then composer cs ; fi

notifications:
  email: true
